import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 'uz' | 'en' | 'ru';

interface LanguageState {
  language: Language;
  setLanguage: (language: Language) => void;
  getText: (key: string) => string;
}

const translations = {
  uz: {
    // Navigation
    home: 'Bosh sahifa',
    matches: 'O\'yinlar',
    teams: 'Jamoalar',
    standings: 'Reyting',
    account: 'Hisob',
    settings: 'Sozlamalar',
    
    // Settings
    appearance: 'Ko\'rinish',
    darkMode: 'Qorong\'u rejim',
    darkModeSubtitle: 'Yorug\' yoki qorong\'u mavzu',
    language: 'Til',
    selectLanguage: 'Til tanlash',
    settingsSubtitle: 'Ilova sozlamalarini boshqaring',
    notifications: 'Bildirishnomalar',
    pushNotifications: 'Push bildirishnomalar',
    autoUpdate: 'Avtomatik yangilanish',
    data: 'Ma\'lumotlar',
    clearCache: 'Cache tozalash',
    downloadData: 'Ma\'lumotlarni yuklab olish',
    about: 'Dastur haqida',
    version: 'Versiya',
    help: 'Yordam',
    privacy: 'Maxfiylik siyosati',
    logout: 'Chiqish',
    logoutSubtitle: 'Hisobingizdan chiqing',
    logoutConfirm: 'Hisobingizdan chiqishni xohlaysizmi?',
    player: 'O\'yinchi',
    
    // Common
    cancel: 'Bekor qilish',
    confirm: 'Tasdiqlash',
    save: 'Saqlash',
    loading: 'Yuklanmoqda...',
    error: 'Xatolik',
    success: 'Muvaffaqiyat',
    
    // Theme
    lightTheme: 'Yorug\' mavzu',
    darkTheme: 'Qorong\'u mavzu',
    
    // Language names
    uzbek: 'O\'zbek',
    english: 'English',
    russian: 'Русский',
    
    // Home Screen
    welcomeToHFL: 'HFL ga xush kelibsiz',
    havasFootballLeague: 'Havas Football League',
    upcomingMatches: 'Kutilayotgan o\'yinlar',
    liveMatches: 'Jonli o\'yinlar',
    noUpcomingMatches: 'Kutilayotgan o\'yinlar yo\'q',
    viewAllMatches: 'Barcha o\'yinlarni ko\'rish',
    
    // Account Screen
    manageAccount: 'Hisobingizni boshqaring',
    transferRequest: 'Transfer arizasi',
    apply: 'Ariza berish',
    submitTransferRequest: 'Transfer ariza berish',
    transferRequestSubtitle: 'Boshqa jamoaga o\'tish uchun ariza',
    applySubtitle: 'O\'yinchi, jamoa yoki liga sifatida ro\'yxatdan o\'ting',
    playerPanel: 'O\'yinchi paneli',
    playerPanelSubtitle: 'Statistikalar va ma\'lumotlar',
    playerLogin: 'O\'yinchi kirish',
    playerLoginSubtitle: 'Mavjud o\'yinchi hisobiga kiring',
    appSettings: 'Ilova sozlamalari',
    aboutSubtitle: 'Ilova versiyasi va ma\'lumotlar',
    playerApplication: 'O\'yinchi Ariza',
    playerApplicationMessage: 'O\'yinchi sifatida ariza berishni xohlaysizmi?',
    teamApplication: 'Jamoa Ariza',
    teamApplicationMessage: 'Jamoa sifatida ariza berishni xohlaysizmi?',
    leagueApplication: 'Liga Ariza',
    leagueApplicationMessage: 'Liga sifatida ariza berishni xohlaysizmi?',
    transferRequestMessage: 'Qanday transfer ariza berishni xohlaysiz?',
    playerTransfer: 'O\'yinchi transfer',
    teamTransfer: 'Jamoa transfer',
    yesContinue: 'Ha, davom etish',
    logoutSuccess: 'Hisobingizdan chiqdingiz',
    logoutError: 'Chiqishda xatolik yuz berdi',
    appVersion: 'HFL Mobile App v1.0.0',
    
    // Application Type Modal
    applicationType: 'Ariza Turi',
    applicationTypeMessage: 'Qanday ariza berishni xohlaysiz?',
    
    // Player Login Screen
    phoneStepSubtitle: 'Telefon raqamingizni kiriting va tasdiqlash kodi oling',
    otpStepSubtitle: 'Telefoningizga yuborilgan tasdiqlash kodini kiriting',
    phoneNumber: 'Telefon raqam',
    sendingCode: 'Kod yuborilmoqda...',
    sendVerificationCode: 'Tasdiqlash kodi yuborish',
    verificationCode: 'Tasdiqlash kodi',
    sentTo: 'raqamiga yuborildi',
    verifying: 'Tekshirilmoqda...',
    verify: 'Tasdiqlash',
    resend: 'Qayta yuborish',
    changePhoneNumber: 'Telefon raqamni o\'zgartirish',
    enterPhoneNumber: 'Telefon raqamini kiriting',
    invalidPhoneFormat: 'Telefon raqami noto\'g\'ri formatda. +998 90 123 45 67 ko\'rinishida kiriting',
    otpSent: 'Tasdiqlash kodi yuborildi',
    otpSendError: 'Kod yuborishda xatolik',
    serverTimeout: 'Server bilan bog\'lanishda timeout. Qayta urinib ko\'ring.',
    serverDown: 'Server ishlamayapti. Iltimos, keyinroq urinib ko\'ring.',
    enterOtpCode: 'Tasdiqlash kodini kiriting',
    otpCodeLength: 'Tasdiqlash kodi 4 xonali bo\'lishi kerak',
    blocked: 'Bloklangan',
    tooManyAttempts: 'Juda ko\'p noto\'g\'ri urinish. 15 daqiqa kutib turing',
    wrongCode: 'Noto\'g\'ri kod',
    otpVerifyError: 'Kod tekshirishda xatolik yuz berdi. Qayta urinib ko\'ring.',
    wait: 'Kuting',
    secondsWait: 'soniya kutib turing',
    goBack: 'Orqaga qaytish',
    
    // Navigation
    matchDetails: 'O\'yin tafsilotlari',
    teamDetails: 'Jamoa tafsilotlari',
    
    // Add Match Screen
    addMatch: 'Yangi o\'yin qo\'shish',
    homeTeam: 'Uy jamoasi',
    awayTeam: 'Mehmon jamoasi',
    venue: 'Maydon',
    league: 'Liga',
    date: 'Sana',
    time: 'Vaqt',
    enterHomeTeam: 'Uy jamoasi nomini kiriting',
    enterAwayTeam: 'Mehmon jamoasi nomini kiriting',
    enterVenue: 'Maydon nomini kiriting',
    enterLeague: 'Liga nomini kiriting',
    adding: 'Qo\'shilmoqda...',
    fillAllFields: 'Barcha maydonlarni to\'ldiring',
    matchAddedSuccessfully: 'O\'yin muvaffaqiyatli qo\'shildi',
    errorAddingMatch: 'O\'yin qo\'shishda xatolik',
    
    // Team Selection Screen
    selectTeam: 'Jamoa Tanlang',
    whichTeamToPlay: 'Qaysi jamoa uchun o\'ynashni xohlaysiz?',
    unknownTeam: 'Noma\'lum jamoa',
    noTeamInfo: 'Jamoa haqida ma\'lumot yo\'q',
    noTeamsAvailable: 'Hozircha jamoalar yo\'q',
    
    // Player Registration Screen
    playerRegistration: 'O\'yinchi Ro\'yxatdan O\'tish',
    teamForRegistration: 'jamoasi uchun ma\'lumotlaringizni kiriting',
    firstName: 'Ism',
    lastName: 'Familiya',
    enterFirstName: 'Ismingizni kiriting',
    enterLastName: 'Familiyangizni kiriting',
    position: 'Pozitsiya',
    selectPosition: 'Pozitsiya tanlang',
    goalkeeper: 'Darvozabon',
    centerBack: 'Markaziy himoyachi',
    leftBack: 'Chap qanot himoyachisi',
    rightBack: 'O\'ng qanot himoyachisi',
    defensiveMidfielder: 'Defensiv yarim himoyachi',
    centerMidfielder: 'Markaziy yarim himoyachi',
    attackingMidfielder: 'Hujumkor yarim himoyachi',
    leftMidfielder: 'Chap qanot yarim himoyachisi',
    rightMidfielder: 'O\'ng qanot yarim himoyachisi',
    leftWinger: 'Chap qanot hujumchisi',
    rightWinger: 'O\'ng qanot hujumchisi',
    striker: 'Markaziy hujumchi',
    centerForward: 'Soxta hujumchi',
    jerseyNumber: 'Forma raqami',
    photo: '3x4 rasm',
    uploading: 'Yuklanmoqda...',
    change: 'O\'zgartirish',
    delete: 'O\'chirish',
    selectPhoto: 'Rasm tanlash',
    submitting: 'Yuborilmoqda...',
    submitApplication: 'Arizani yuborish',
    applicationSubmitted: 'Arizangiz yuborildi. Admin tomonidan ko\'rib chiqilgandan so\'ng sizga xabar beriladi.',
    ok: 'OK',
    unknownError: 'Noma\'lum xatolik',
    applicationError: 'Ariza yuborishda xatolik yuz berdi',
    checkInternetConnection: 'Internet aloqasini tekshiring',
    serverConnectionError: 'Server bilan aloqa yo\'q. Internet aloqasini tekshiring.',
    imageSelectionError: 'Rasm tanlashda xatolik yuz berdi',
    
    // Team Application Screen
    teamApplication: 'Jamoa Ariza Berish',
    teamApplicationSubtitle: 'Yangi jamoa sifatida ligaga qo\'shilish uchun ariza',
    teamName: 'Jamoa nomi',
    enterTeamName: 'Jamoa nomini kiriting',
    foundedDate: 'Tashkil topgan sana',
    teamLogo: 'Jamoa logosi',
    teamColor: 'Jamoa rangi',
    teamDescription: 'Jamoa haqida',
    enterTeamDescription: 'Jamoa haqida qisqacha ma\'lumot',
    contactPerson: 'Aloqa shaxsi',
    enterContactPerson: 'Aloqa shaxsi ismi',
    selectLogo: 'Logo tanlash',
    logoUploadedSuccessfully: 'Logo muvaffaqiyatli yuklandi',
    logoUploadError: 'Logo yuklashda xatolik yuz berdi',
    logoSelectionError: 'Logo tanlashda xatolik yuz berdi',
    permissionRequired: 'Ruxsat kerak',
    galleryPermissionRequired: 'Logo tanlash uchun galereya ruxsati kerak',
    teamApplicationSubmitted: 'Jamoa arizasi yuborildi. Admin tomonidan ko\'rib chiqilgandan so\'ng sizga xabar beriladi.',
    
    // League Application Screen
    leagueApplication: 'Liga Ariza',
    leagueApplicationSubtitle: 'Yangi liga sifatida ariza berish',
    leagueName: 'Liga nomi',
    enterLeagueName: 'Liga nomini kiriting',
    leagueDescription: 'Liga haqida',
    enterLeagueDescription: 'Liga haqida qisqacha ma\'lumot',
    enterFullName: 'To\'liq ism',
    enterLeagueAddress: 'Liga manzili',
    website: 'Veb-sayt',
    leagueApplicationSubmitted: 'Liga arizasi yuborildi. Admin tomonidan ko\'rib chiqilgandan so\'ng sizga xabar beriladi.',
    
    // Matches Screen
    all: 'Barchasi',
    live: 'Jonli',
    upcoming: 'Kutilayotgan',
    finished: 'Tugagan',
    scheduled: 'Rejalashtirilgan',
    unknown: 'Noma\'lum',
    noMatchesFound: 'O\'yinlar topilmadi',
    noMatchesFoundForFilter: '{filter} o\'yinlar topilmadi',
    
    // Match Detail Screen
    matchDetails: 'O\'yin Tafsilotlari',
    matchInformation: 'O\'yin Ma\'lumotlari',
    dateAndTime: 'Sana va Vaqt',
    venue: 'Maydon',
    referee: 'Hakam',
    liveStream: 'Jonli Ko\'rish',
    watchOnYouTube: 'YouTube da Ko\'rish',
    matchInProgress: 'O\'yin hozir jarayonda. Hisoblar real vaqtda yangilanadi.',
    cannotOpenYouTubeLink: 'YouTube linkini ochish mumkin emas',
    errorOpeningYouTubeLink: 'YouTube linkini ochishda xatolik yuz berdi',
    goBack: 'Orqaga qaytish',
    
    // Admin Match Edit Screen
    editMatch: 'O\'yin Tahrirlash',
    score: 'Hisob',
    homeTeam: 'Uy jamoasi',
    awayTeam: 'Mehmon jamoasi',
    status: 'Holat',
    enterScore: 'Hisobni kiriting',
    matchUpdated: 'O\'yin yangilandi',
    save: 'Saqlash',
    
    // Teams Screen
    teams: 'Jamoalar',
    teamsLoading: 'Jamoalar yuklanmoqda...',
    noTeamsAvailable: 'Hozircha jamoalar yo\'q',
    teamIdNotFound: 'Jamoa ID topilmadi',
    teamColor: 'Jamoa rangi',
    unknownTeam: 'Noma\'lum jamoa',
    players: 'O\'yinchi',
    noPlayersFound: 'O\'yinchi topilmadi',
    teamInformation: 'Jamoa ma\'lumotlari',
    teamName: 'Jamoa nomi',
    totalPlayers: 'Jami o\'yinchi',
    positionBreakdown: 'Pozitsiya bo\'yicha taqsimot',
    active: 'Faol',
    inactive: 'Nofaol',
    suspended: 'Suspensiya',
  },
  en: {
    // Navigation
    home: 'Home',
    matches: 'Matches',
    teams: 'Teams',
    standings: 'Standings',
    account: 'Account',
    settings: 'Settings',
    
    // Settings
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    darkModeSubtitle: 'Light or dark theme',
    language: 'Language',
    selectLanguage: 'Select Language',
    settingsSubtitle: 'Manage app settings',
    notifications: 'Notifications',
    pushNotifications: 'Push Notifications',
    autoUpdate: 'Auto Update',
    data: 'Data',
    clearCache: 'Clear Cache',
    downloadData: 'Download Data',
    about: 'About',
    version: 'Version',
    help: 'Help',
    privacy: 'Privacy Policy',
    logout: 'Logout',
    logoutSubtitle: 'Sign out of your account',
    logoutConfirm: 'Are you sure you want to sign out?',
    player: 'Player',
    
    // Common
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    
    // Theme
    lightTheme: 'Light Theme',
    darkTheme: 'Dark Theme',
    
    // Language names
    uzbek: 'O\'zbek',
    english: 'English',
    russian: 'Русский',
    
    // Home Screen
    welcomeToHFL: 'Welcome to HFL',
    havasFootballLeague: 'Havas Football League',
    upcomingMatches: 'Upcoming Matches',
    liveMatches: 'Live Matches',
    noUpcomingMatches: 'No upcoming matches',
    viewAllMatches: 'View All Matches',
    
    // Account Screen
    manageAccount: 'Manage your account',
    transferRequest: 'Transfer Request',
    apply: 'Apply',
    submitTransferRequest: 'Submit Transfer Request',
    transferRequestSubtitle: 'Request to transfer to another team',
    applySubtitle: 'Register as player, team or league',
    playerPanel: 'Player Panel',
    playerPanelSubtitle: 'Statistics and information',
    playerLogin: 'Player Login',
    playerLoginSubtitle: 'Sign in to existing player account',
    appSettings: 'App settings',
    aboutSubtitle: 'App version and information',
    playerApplication: 'Player Application',
    playerApplicationMessage: 'Do you want to apply as a player?',
    teamApplication: 'Team Application',
    teamApplicationMessage: 'Do you want to apply as a team?',
    leagueApplication: 'League Application',
    leagueApplicationMessage: 'Do you want to apply as a league?',
    transferRequestMessage: 'What type of transfer request do you want to make?',
    playerTransfer: 'Player Transfer',
    teamTransfer: 'Team Transfer',
    yesContinue: 'Yes, Continue',
    logoutSuccess: 'You have been logged out',
    logoutError: 'Error occurred during logout',
    appVersion: 'HFL Mobile App v1.0.0',
    
    // Application Type Modal
    applicationType: 'Application Type',
    applicationTypeMessage: 'What type of application do you want to submit?',
    
    // Player Login Screen
    phoneStepSubtitle: 'Enter your phone number and get a verification code',
    otpStepSubtitle: 'Enter the verification code sent to your phone',
    phoneNumber: 'Phone Number',
    sendingCode: 'Sending code...',
    sendVerificationCode: 'Send Verification Code',
    verificationCode: 'Verification Code',
    sentTo: 'sent to',
    verifying: 'Verifying...',
    verify: 'Verify',
    resend: 'Resend',
    changePhoneNumber: 'Change Phone Number',
    enterPhoneNumber: 'Enter phone number',
    invalidPhoneFormat: 'Invalid phone format. Enter in +998 90 123 45 67 format',
    otpSent: 'Verification code sent',
    otpSendError: 'Error sending code',
    serverTimeout: 'Server connection timeout. Please try again.',
    serverDown: 'Server is down. Please try again later.',
    enterOtpCode: 'Enter verification code',
    otpCodeLength: 'Verification code must be 4 digits',
    blocked: 'Blocked',
    tooManyAttempts: 'Too many wrong attempts. Wait 15 minutes',
    wrongCode: 'Wrong code',
    otpVerifyError: 'Error verifying code. Please try again.',
    wait: 'Wait',
    secondsWait: 'seconds wait',
    goBack: 'Go Back',
    
    // Navigation
    matchDetails: 'Match Details',
    teamDetails: 'Team Details',
    
    // Add Match Screen
    addMatch: 'Add New Match',
    homeTeam: 'Home Team',
    awayTeam: 'Away Team',
    venue: 'Venue',
    league: 'League',
    date: 'Date',
    time: 'Time',
    enterHomeTeam: 'Enter home team name',
    enterAwayTeam: 'Enter away team name',
    enterVenue: 'Enter venue name',
    enterLeague: 'Enter league name',
    adding: 'Adding...',
    fillAllFields: 'Please fill all fields',
    matchAddedSuccessfully: 'Match added successfully',
    errorAddingMatch: 'Error adding match',
    
    // Team Selection Screen
    selectTeam: 'Select Team',
    whichTeamToPlay: 'Which team do you want to play for?',
    unknownTeam: 'Unknown Team',
    noTeamInfo: 'No team information',
    noTeamsAvailable: 'No teams available',
    
    // Player Registration Screen
    playerRegistration: 'Player Registration',
    teamForRegistration: 'team for registration',
    firstName: 'First Name',
    lastName: 'Last Name',
    enterFirstName: 'Enter your first name',
    enterLastName: 'Enter your last name',
    position: 'Position',
    selectPosition: 'Select position',
    goalkeeper: 'Goalkeeper',
    centerBack: 'Center Back',
    leftBack: 'Left Back',
    rightBack: 'Right Back',
    defensiveMidfielder: 'Defensive Midfielder',
    centerMidfielder: 'Center Midfielder',
    attackingMidfielder: 'Attacking Midfielder',
    leftMidfielder: 'Left Midfielder',
    rightMidfielder: 'Right Midfielder',
    leftWinger: 'Left Winger',
    rightWinger: 'Right Winger',
    striker: 'Striker',
    centerForward: 'Center Forward',
    jerseyNumber: 'Jersey Number',
    photo: '3x4 Photo',
    uploading: 'Uploading...',
    change: 'Change',
    delete: 'Delete',
    selectPhoto: 'Select Photo',
    submitting: 'Submitting...',
    submitApplication: 'Submit Application',
    applicationSubmitted: 'Your application has been submitted. You will be notified after admin review.',
    ok: 'OK',
    unknownError: 'Unknown error',
    applicationError: 'Error submitting application',
    checkInternetConnection: 'Check internet connection',
    serverConnectionError: 'No connection to server. Check internet connection.',
    imageSelectionError: 'Error selecting image',
    
    // Team Application Screen
    teamApplication: 'Team Application',
    teamApplicationSubtitle: 'Application to join the league as a new team',
    teamName: 'Team Name',
    enterTeamName: 'Enter team name',
    foundedDate: 'Founded Date',
    teamLogo: 'Team Logo',
    teamColor: 'Team Color',
    teamDescription: 'About Team',
    enterTeamDescription: 'Brief information about the team',
    contactPerson: 'Contact Person',
    enterContactPerson: 'Contact person name',
    selectLogo: 'Select Logo',
    logoUploadedSuccessfully: 'Logo uploaded successfully',
    logoUploadError: 'Error uploading logo',
    logoSelectionError: 'Error selecting logo',
    permissionRequired: 'Permission Required',
    galleryPermissionRequired: 'Gallery permission required to select logo',
    teamApplicationSubmitted: 'Team application submitted. You will be notified after admin review.',
    
    // League Application Screen
    leagueApplication: 'League Application',
    leagueApplicationSubtitle: 'Apply as a new league',
    leagueName: 'League Name',
    enterLeagueName: 'Enter league name',
    leagueDescription: 'About League',
    enterLeagueDescription: 'Brief information about the league',
    enterFullName: 'Full name',
    enterLeagueAddress: 'League address',
    website: 'Website',
    leagueApplicationSubmitted: 'League application submitted. You will be notified after admin review.',
    
    // Matches Screen
    all: 'All',
    live: 'Live',
    upcoming: 'Upcoming',
    finished: 'Finished',
    scheduled: 'Scheduled',
    unknown: 'Unknown',
    noMatchesFound: 'No matches found',
    noMatchesFoundForFilter: 'No {filter} matches found',
    
    // Match Detail Screen
    matchDetails: 'Match Details',
    matchInformation: 'Match Information',
    dateAndTime: 'Date and Time',
    venue: 'Venue',
    referee: 'Referee',
    liveStream: 'Live Stream',
    watchOnYouTube: 'Watch on YouTube',
    matchInProgress: 'Match is in progress. Scores are updated in real time.',
    cannotOpenYouTubeLink: 'Cannot open YouTube link',
    errorOpeningYouTubeLink: 'Error opening YouTube link',
    goBack: 'Go Back',
    
    // Admin Match Edit Screen
    editMatch: 'Edit Match',
    score: 'Score',
    homeTeam: 'Home Team',
    awayTeam: 'Away Team',
    status: 'Status',
    enterScore: 'Enter score',
    matchUpdated: 'Match updated',
    save: 'Save',
    
    // Teams Screen
    teams: 'Teams',
    teamsLoading: 'Loading teams...',
    noTeamsAvailable: 'No teams available',
    teamIdNotFound: 'Team ID not found',
    teamColor: 'Team color',
    unknownTeam: 'Unknown team',
    players: 'Players',
    noPlayersFound: 'No players found',
    teamInformation: 'Team information',
    teamName: 'Team name',
    totalPlayers: 'Total players',
    positionBreakdown: 'Position breakdown',
    active: 'Active',
    inactive: 'Inactive',
    suspended: 'Suspended',
  },
  ru: {
    // Navigation
    home: 'Главная',
    matches: 'Матчи',
    teams: 'Команды',
    standings: 'Рейтинг',
    account: 'Аккаунт',
    settings: 'Настройки',
    
    // Settings
    appearance: 'Внешний вид',
    darkMode: 'Темная тема',
    darkModeSubtitle: 'Светлая или темная тема',
    language: 'Язык',
    selectLanguage: 'Выберите язык',
    settingsSubtitle: 'Управление настройками приложения',
    notifications: 'Уведомления',
    pushNotifications: 'Push уведомления',
    autoUpdate: 'Автообновление',
    data: 'Данные',
    clearCache: 'Очистить кэш',
    downloadData: 'Скачать данные',
    about: 'О программе',
    version: 'Версия',
    help: 'Помощь',
    privacy: 'Политика конфиденциальности',
    logout: 'Выйти',
    logoutSubtitle: 'Выйти из аккаунта',
    logoutConfirm: 'Вы уверены, что хотите выйти?',
    player: 'Игрок',
    
    // Common
    cancel: 'Отмена',
    confirm: 'Подтвердить',
    save: 'Сохранить',
    loading: 'Загрузка...',
    error: 'Ошибка',
    success: 'Успешно',
    
    // Theme
    lightTheme: 'Светлая тема',
    darkTheme: 'Темная тема',
    
    // Language names
    uzbek: 'O\'zbek',
    english: 'English',
    russian: 'Русский',
    
    // Home Screen
    welcomeToHFL: 'Добро пожаловать в HFL',
    havasFootballLeague: 'Havas Football League',
    upcomingMatches: 'Предстоящие матчи',
    liveMatches: 'Прямые матчи',
    noUpcomingMatches: 'Нет предстоящих матчей',
    viewAllMatches: 'Посмотреть все матчи',
    
    // Account Screen
    manageAccount: 'Управляйте своим аккаунтом',
    transferRequest: 'Запрос на перевод',
    apply: 'Подать заявку',
    submitTransferRequest: 'Подать запрос на перевод',
    transferRequestSubtitle: 'Запрос на перевод в другую команду',
    applySubtitle: 'Зарегистрироваться как игрок, команда или лига',
    playerPanel: 'Панель игрока',
    playerPanelSubtitle: 'Статистика и информация',
    playerLogin: 'Вход игрока',
    playerLoginSubtitle: 'Войти в существующий аккаунт игрока',
    appSettings: 'Настройки приложения',
    aboutSubtitle: 'Версия приложения и информация',
    playerApplication: 'Заявка игрока',
    playerApplicationMessage: 'Хотите подать заявку как игрок?',
    teamApplication: 'Заявка команды',
    teamApplicationMessage: 'Хотите подать заявку как команда?',
    leagueApplication: 'Заявка лиги',
    leagueApplicationMessage: 'Хотите подать заявку как лига?',
    transferRequestMessage: 'Какой тип запроса на перевод вы хотите сделать?',
    playerTransfer: 'Перевод игрока',
    teamTransfer: 'Перевод команды',
    yesContinue: 'Да, продолжить',
    logoutSuccess: 'Вы вышли из системы',
    logoutError: 'Произошла ошибка при выходе',
    appVersion: 'HFL Mobile App v1.0.0',
    
    // Application Type Modal
    applicationType: 'Тип заявки',
    applicationTypeMessage: 'Какой тип заявки вы хотите подать?',
    
    // Player Login Screen
    phoneStepSubtitle: 'Введите номер телефона и получите код подтверждения',
    otpStepSubtitle: 'Введите код подтверждения, отправленный на ваш телефон',
    phoneNumber: 'Номер телефона',
    sendingCode: 'Отправка кода...',
    sendVerificationCode: 'Отправить код подтверждения',
    verificationCode: 'Код подтверждения',
    sentTo: 'отправлен на',
    verifying: 'Проверка...',
    verify: 'Подтвердить',
    resend: 'Отправить повторно',
    changePhoneNumber: 'Изменить номер телефона',
    enterPhoneNumber: 'Введите номер телефона',
    invalidPhoneFormat: 'Неверный формат телефона. Введите в формате +998 90 123 45 67',
    otpSent: 'Код подтверждения отправлен',
    otpSendError: 'Ошибка отправки кода',
    serverTimeout: 'Таймаут соединения с сервером. Попробуйте снова.',
    serverDown: 'Сервер не работает. Попробуйте позже.',
    enterOtpCode: 'Введите код подтверждения',
    otpCodeLength: 'Код подтверждения должен быть 4-значным',
    blocked: 'Заблокирован',
    tooManyAttempts: 'Слишком много неправильных попыток. Подождите 15 минут',
    wrongCode: 'Неверный код',
    otpVerifyError: 'Ошибка проверки кода. Попробуйте снова.',
    wait: 'Подождите',
    secondsWait: 'секунд подождите',
    goBack: 'Назад',
    
    // Navigation
    matchDetails: 'Детали матча',
    teamDetails: 'Детали команды',
    
    // Add Match Screen
    addMatch: 'Добавить новый матч',
    homeTeam: 'Домашняя команда',
    awayTeam: 'Гостевая команда',
    venue: 'Стадион',
    league: 'Лига',
    date: 'Дата',
    time: 'Время',
    enterHomeTeam: 'Введите название домашней команды',
    enterAwayTeam: 'Введите название гостевой команды',
    enterVenue: 'Введите название стадиона',
    enterLeague: 'Введите название лиги',
    adding: 'Добавление...',
    fillAllFields: 'Заполните все поля',
    matchAddedSuccessfully: 'Матч успешно добавлен',
    errorAddingMatch: 'Ошибка добавления матча',
    
    // Team Selection Screen
    selectTeam: 'Выберите команду',
    whichTeamToPlay: 'За какую команду вы хотите играть?',
    unknownTeam: 'Неизвестная команда',
    noTeamInfo: 'Нет информации о команде',
    noTeamsAvailable: 'Команды недоступны',
    
    // Player Registration Screen
    playerRegistration: 'Регистрация игрока',
    teamForRegistration: 'команды для регистрации',
    firstName: 'Имя',
    lastName: 'Фамилия',
    enterFirstName: 'Введите ваше имя',
    enterLastName: 'Введите вашу фамилию',
    position: 'Позиция',
    selectPosition: 'Выберите позицию',
    goalkeeper: 'Вратарь',
    centerBack: 'Центральный защитник',
    leftBack: 'Левый защитник',
    rightBack: 'Правый защитник',
    defensiveMidfielder: 'Опорный полузащитник',
    centerMidfielder: 'Центральный полузащитник',
    attackingMidfielder: 'Атакующий полузащитник',
    leftMidfielder: 'Левый полузащитник',
    rightMidfielder: 'Правый полузащитник',
    leftWinger: 'Левый вингер',
    rightWinger: 'Правый вингер',
    striker: 'Нападающий',
    centerForward: 'Центральный нападающий',
    jerseyNumber: 'Номер игрока',
    photo: 'Фото 3x4',
    uploading: 'Загрузка...',
    change: 'Изменить',
    delete: 'Удалить',
    selectPhoto: 'Выбрать фото',
    submitting: 'Отправка...',
    submitApplication: 'Отправить заявку',
    applicationSubmitted: 'Ваша заявка отправлена. Вы будете уведомлены после рассмотрения администратором.',
    ok: 'ОК',
    unknownError: 'Неизвестная ошибка',
    applicationError: 'Ошибка отправки заявки',
    checkInternetConnection: 'Проверьте интернет-соединение',
    serverConnectionError: 'Нет соединения с сервером. Проверьте интернет-соединение.',
    imageSelectionError: 'Ошибка выбора изображения',
    
    // Team Application Screen
    teamApplication: 'Заявка команды',
    teamApplicationSubtitle: 'Заявка на вступление в лигу в качестве новой команды',
    teamName: 'Название команды',
    enterTeamName: 'Введите название команды',
    foundedDate: 'Дата основания',
    teamLogo: 'Логотип команды',
    teamColor: 'Цвет команды',
    teamDescription: 'О команде',
    enterTeamDescription: 'Краткая информация о команде',
    contactPerson: 'Контактное лицо',
    enterContactPerson: 'Имя контактного лица',
    selectLogo: 'Выбрать логотип',
    logoUploadedSuccessfully: 'Логотип успешно загружен',
    logoUploadError: 'Ошибка загрузки логотипа',
    logoSelectionError: 'Ошибка выбора логотипа',
    permissionRequired: 'Требуется разрешение',
    galleryPermissionRequired: 'Требуется разрешение галереи для выбора логотипа',
    teamApplicationSubmitted: 'Заявка команды отправлена. Вы будете уведомлены после рассмотрения администратором.',
    
    // League Application Screen
    leagueApplication: 'Заявка лиги',
    leagueApplicationSubtitle: 'Подать заявку как новая лига',
    leagueName: 'Название лиги',
    enterLeagueName: 'Введите название лиги',
    leagueDescription: 'О лиге',
    enterLeagueDescription: 'Краткая информация о лиге',
    enterFullName: 'Полное имя',
    enterLeagueAddress: 'Адрес лиги',
    website: 'Веб-сайт',
    leagueApplicationSubmitted: 'Заявка лиги отправлена. Вы будете уведомлены после рассмотрения администратором.',
    
    // Matches Screen
    all: 'Все',
    live: 'В прямом эфире',
    upcoming: 'Предстоящие',
    finished: 'Завершенные',
    scheduled: 'Запланированные',
    unknown: 'Неизвестно',
    noMatchesFound: 'Матчи не найдены',
    noMatchesFoundForFilter: 'Матчи {filter} не найдены',
    
    // Match Detail Screen
    matchDetails: 'Детали матча',
    matchInformation: 'Информация о матче',
    dateAndTime: 'Дата и время',
    venue: 'Место проведения',
    referee: 'Судья',
    liveStream: 'Прямая трансляция',
    watchOnYouTube: 'Смотреть на YouTube',
    matchInProgress: 'Матч в процессе. Счет обновляется в реальном времени.',
    cannotOpenYouTubeLink: 'Не удается открыть ссылку YouTube',
    errorOpeningYouTubeLink: 'Ошибка при открытии ссылки YouTube',
    goBack: 'Назад',
    
    // Admin Match Edit Screen
    editMatch: 'Редактировать матч',
    score: 'Счет',
    homeTeam: 'Домашняя команда',
    awayTeam: 'Гостевая команда',
    status: 'Статус',
    enterScore: 'Введите счет',
    matchUpdated: 'Матч обновлен',
    save: 'Сохранить',
    
    // Teams Screen
    teams: 'Команды',
    teamsLoading: 'Загрузка команд...',
    noTeamsAvailable: 'Команды недоступны',
    teamIdNotFound: 'ID команды не найден',
    teamColor: 'Цвет команды',
    unknownTeam: 'Неизвестная команда',
    players: 'Игроки',
    noPlayersFound: 'Игроки не найдены',
    teamInformation: 'Информация о команде',
    teamName: 'Название команды',
    totalPlayers: 'Всего игроков',
    positionBreakdown: 'Распределение по позициям',
    active: 'Активный',
    inactive: 'Неактивный',
    suspended: 'Отстранен',
  },
};

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'uz',
      setLanguage: (language) => set({ language }),
      getText: (key: string) => {
        const currentLanguage = get().language;
        return translations[currentLanguage][key] || key;
      },
    }),
    {
      name: 'language-storage',
    }
  )
);

export const useLanguage = () => {
  const { language, setLanguage, getText } = useLanguageStore();
  return { language, setLanguage, getText };
};
