const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
function mount(values,state='active') {const effects=[],setters=[];let hook=0,listener;const appState={currentState:state,addEventListener:(_,fn)=>{listener=fn;return{remove(){}}}};
 const React={createElement:()=>({})};const hooks={__esModule:true,default:React,useEffect:fn=>effects.push(fn),useRef:v=>({current:v}),useState:v=>{const i=hook++;return[v,x=>setters[i]=x];}};
 const imports={'react':hooks,'react-native':{AppState:appState,Platform:{OS:'android'},Animated:{Value:class{}},AccessibilityInfo:{isReduceMotionEnabled:async()=>false},StyleSheet:{create:x=>x}},'@react-native-async-storage/async-storage':{__esModule:true,default:{getItem:async k=>values.get(k)||null,setItem:async(k,v)=>values.set(k,v)}},'@expo/vector-icons':{},'react-i18next':{useTranslation:()=>({t:x=>x})},'../store/useThemeStore':{useThemeStore:()=>({colors:{}})}};
 const out={};new Function('require','exports',ts.transpileModule(fs.readFileSync('components/AppRatingPrompt.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.React}}).outputText)(n=>imports[n],out);out.default({enabled:true});effects[0]();return{setters,active(){appState.currentState='active';listener('active');}};
}
const flush=async()=>{await new Promise(r=>setImmediate(r));};
test('third app launch prompts even when startup was not active; first two do not',async()=>{const values=new Map();for(let n=1;n<=3;n++){const app=mount(values,'background');await flush();assert.notEqual(app.setters[0],true);app.active();assert.equal(app.setters[0]===true,n===3);}});
test('finished ratings and later cooldown suppress prompts',async()=>{for(const saved of [{visits:4,done:true},{visits:4,next:Date.now()+86400000}]){const app=mount(new Map([['@amatora_rating_prompt_v1',JSON.stringify(saved)]]));await flush();assert.notEqual(app.setters[0],true);}});
