const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');
test('transfer refocus restarts an aborted read even when cached session object is unchanged',async()=>{
 const realReact=require('react');const slots=[];let at=0,dirty=true;const effects=[];let focused;const requests=[];
 const session={actor:'captain',subjectId:'12345678-1234-1234-1234-123456789abc',token:'a'.repeat(64),expiresAt:Date.now()+60000};
 function effect(fn,deps){const index=at++,old=slots[index];if(!old||deps.some((d,i)=>!Object.is(d,old.deps[i]))){slots[index]={deps,cleanup:old?.cleanup};effects.push(()=>{slots[index].cleanup?.();slots[index].cleanup=fn();});}}
 const react={...realReact,useState(initial){const index=at++;if(!slots[index])slots[index]={value:typeof initial==='function'?initial():initial};return[slots[index].value,value=>{const next=typeof value==='function'?value(slots[index].value):value;if(!Object.is(next,slots[index].value)){slots[index].value=next;dirty=true;}}];},useRef(value){const index=at++;if(!slots[index])slots[index]={current:value};return slots[index];},useEffect:effect,useCallback(fn,deps){const index=at++,old=slots[index];if(!old||deps.some((d,i)=>!Object.is(d,old.deps[i])))slots[index]={deps,value:fn};return slots[index].value;}};
 class TransferApiError extends Error{constructor(status){super();this.status=status;}}
 const imports={react,'react-native':{StyleSheet:{create:x=>x},Platform:{OS:'android'},Alert:{alert(){}},View:'View',Text:'Text',FlatList:'FlatList',TextInput:'TextInput',Pressable:'Pressable',ActivityIndicator:'Spinner'},'react-native-safe-area-context':{SafeAreaView:'SafeAreaView'},'@expo/vector-icons':{Ionicons:'Icon'},'@react-navigation/native':{useFocusEffect:fn=>effect(()=>{focused=fn;return fn();},[fn])},'react-i18next':{useTranslation:()=>({t:translate,i18n:{language:'uz'}})},'../store/useAuthStore':{useAuthStore:()=>({user:{role:'manager',id:session.subjectId},isGuest:false})},'../store/useThemeStore':{useThemeStore:()=>({isDark:true})},'../constants/homeTheme':{getHomeScreenColors:()=>({})},'../components/SmartImage':{default:'Image',__esModule:true},'../services/transferLoginStorage':{restoreTransferLoginSession:async()=>session,revokeTransferLoginSession:async()=>{}},'../services/transferAppService':{TransferApiError,getTransferSession:()=>session,clearTransferSession(){},transferAppService:{page(s,d,a,f,signal){return new Promise((resolve,reject)=>{requests.push({resolve,signal});signal.addEventListener('abort',()=>reject(new TransferApiError(0)));});}}}};
 function translate(key){return key;}
 const output={};new Function('require','exports',ts.transpileModule(fs.readFileSync('screens/TransferScreen.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText)(name=>{if(!(name in imports))throw Error(name);return imports[name];},output);
 async function settle(){for(let i=0;i<16;i++){if(dirty){dirty=false;at=0;output.default({navigation:{},route:{}});while(effects.length)effects.shift()();}await Promise.resolve();}}
 await settle();assert.equal(requests.length,1);focused();await settle();assert.equal(requests[0].signal.aborted,true);assert.equal(requests.length,2);
 requests[1].resolve({items:[],next_cursor:null,transfer_window_open:true});await settle();
 // loading is the eighth state hook after focus callback and direction/items/cursor.
 assert.equal(slots[9].value,false);
});
